spring:
  datasource:
    url: jdbc:mysql://gym-crm-database.csetfm4jlkk1.eu-west-3.rds.amazonaws.com:3306/gym_crm_database
    username: admin
    password: Admin12#
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

aws:
  queue:
    name: 
  accessKey: 
  secretKey: 
  cloud:
    aws:
      region:
        static: eu-west-3
        stack:
          auto: false


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000


management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

server:
  error:
    include-stacktrace: never



